builds:
  - binary: konfig
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: konfig
    homepage: https://github.com/ppcool1163/konfig
    tap:
      owner: ppcool1163
      name: homebrew-tap
    commit_author:
      name: ppcool1163
      email: prashantppmsd2405@gmail.com

checksum:
  name_template: 'checksums.txt'